import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav className='w-full flex gap-3'>
          <Link className='text-blue-500' href='/'>
            Home
          </Link>
          |
          <Link className='text-blue-500' href='/notes'>
            notes
          </Link>
        </nav>
        <div className='max-w-[1440px] w-full px-10 mx-auto'>{children}</div>
        {modal}
      </body>
    </html>
  );
}
